import * as VectorIcons from '@expo/vector-icons';
import { chunk } from 'lodash';
import Layout from './Layout';

export const iconSets = [
  {
    key: 'AntDesign',
    data: [
      'creditcard',
      'book',
      'frown',
      'meho',
      'meh',
      'shoppingcart',
      'team',
      'user',
      'phone',
      'camera',
      'smile-circle',
      'smileo',
      'frowno',
      'github',
      'heart',
      'hearto',
      'mobile1',
      'key',
      'skin',
      'tool',
      'car',
      'isv',
      'gift',
      'idcard',
      'rest',
      'android1',
      'aliwangwang',
    ],
  },

  {
    key: 'Entypo',
    data: [
      'aircraft',
      'attachment',
      'baidu',
      'battery',
      'beamed-note',
      'bell',
      'blackboard',
      'book',
      'bowl',
      'box',
      'briefcase',
      'brush',
      'bucket',
      'bug',
      'cake',
      'calculator',
      'clapperboard',
      'cup',
      'drink',
      'drop',
      'edit',
      'flashlight',
      'flat-brush',
      'flower',
      'keyboard',
      'laptop',
      'light-bulb',
      'pin',
      'scissors',
      'shopping-bag',
      'shopping-basket',
      'video',
      'video-camera',
    ],
  },

  {
    key: 'FontAwesome',
    data: [
      'star',
      'film',
      'home',
      'road',
      'photo',
      'asterisk',
      'fire',
      'eye',
      'truck',
      'coffee',
      'cutlery',
      'ambulance',
      'medkit',
      'beer',
      'desktop',
      'binoculars',
      'plug',
      'eyedropper',
      'birthday-cake',
      'bicycle',
      'bus',
      'ship',
      'motorcycle',
      'heartbeat',
      'optin-monster',
      'reddit-alien',
      'fort-awesome',
      'shopping-bag',
      'shopping-basket',
      'bath',
      'shower',
      'grav',
    ],
  },
];

const asList = iconSets
  .map(subset => subset.data.map(name => ({ key: `${subset.key}|||${name}`, name, subset: VectorIcons[subset.key] })))
  .flat();

export default chunk(
  asList,
  Math.floor(Layout.window.width / /* icon width */ (25 + /* margin left & right */ 10 * 2)) * /* num of rows */ 4
).map((data, idx) => ({ key: `page-${idx}`, data }));
